# -*- coding: utf-8 -*-
"""prueba1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biEB1Bo7yfVltHjrvLFOaFwMUtx_pydp
"""

# prompt: ejemplo de listas en python

# Crear una lista vacía
my_list = []

# Crear una lista con elementos
fruits = ["apple", "banana", "cherry"]

# Acceder a elementos de la lista (el índice comienza en 0)
print(fruits[0])  # Imprime "apple"
print(fruits[1])  # Imprime "banana"

# Modificar un elemento de la lista
fruits[1] = "orange"
print(fruits)  # Imprime ["apple", "orange", "cherry"]


# Agregar elementos a la lista
fruits.append("grape")
print(fruits) # Imprime ["apple", "orange", "cherry", "grape"]

# Insertar un elemento en una posición específica
fruits.insert(1, "mango")  # Inserta "mango" en la posición 1
print(fruits) # Imprime ["apple", "mango", "orange", "cherry", "grape"]


# Eliminar elementos de la lista
fruits.remove("orange")  # Elimina la primera ocurrencia de "orange"
print(fruits) # Imprime ["apple", "mango", "cherry", "grape"]

# Eliminar un elemento por su índice
del fruits[0]
print(fruits)  # Imprime ["mango", "cherry", "grape"]


# Obtener la longitud de una lista
print(len(fruits)) # Imprime 3


# Iterar sobre una lista
for fruit in fruits:
    print(fruit)


# Comprobar si un elemento está en la lista
if "cherry" in fruits:
    print("Cherry is in the list")

# Listas anidadas
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix[0][1]) # Imprime 2